stages:
  - prepare-build
  - test
  - build
  - tag-build
  - deploy

# cache:
#   paths:
#     - ~/.cache/pip/

# env_check:
#   stage: prepare-build
#   image: alpine
#   script: 
#     - sleep 1s
#     - cat /etc/os-release
#     - touch testFile
#     - mkdir testDir
#     - mv testFile testDir/
#   artifacts:
#     paths:
#       - testDir/
    

# git_check:
#   stage: prepare-build
#   image: alpine/git
#   script:
#     - echo "check git revision"
#     - git log -1

   

# code_scan:
#   stage: test
#   image: newtmitch/sonar-scanner
#   variables:
#     sonar_token: 6063542555276c71fa96a481f23fa07346f5e655 
#   script:
#     - echo "scanning"
#     - ls 
#     - ls | grep test
#     # - sonar-scanner -Dsonar.projectKey=Tonyqu123_kaniko -Dsonar.organization=tonyqu123 -Dsonar.sources=. -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$sonar_token -Dsonar.scm.disabled=true
#   dependencies:
#     - env_check

# build_release:
#   image: gcr.io/kaniko-project/executor:debug
#   stage: build
#   variables:
#     CI_REGISTRY_IMAGE: "hub.eurekacloud.io/s4/build-kaniko-gitlab"
#     CI_COMMIT_TAG: "release"
#   before_script:
#     - echo $CI_PROJECT_DIR
#     - pwd
#   script:
#     - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/deploy/Dockerfile --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG

# build_debug:
#   image: gcr.io/kaniko-project/executor:debug
#   stage: build
#   allow_failure: true
#   variables:
#     CI_REGISTRY_IMAGE: "hub.eurekacloud.io/s4/build-kaniko-gitlab"
#     CI_COMMIT_TAG: "debug"
#   before_script:
#     - echo $CI_PROJECT_DIR
#     - pwd
#   script:
#     - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/deploy/Dockerfile_debug --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG

.prep_skaffold: &prep_skaffold
  variables:
    TOOLS_DIR_NAME: tools
  before_script:
    - echo "check skaffold"
    - ls -d */ | grep $TOOLS_DIR_NAME || mkdir $TOOLS_DIR_NAME &&
      curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64 &&
      mv skaffold $TOOLS_DIR_NAME/ &&
      export PATH=$PATH:$PWD/$TOOLS_DIR_NAME
    - ls | grep $TOOLS_DIR_NAME
    - ls $TOOLS_DIR_NAME/

skaffold_build:
  image: byrnedo/alpine-curl
  stage: tag-build
  <<: *prep_skaffold
  script:
    - echo $CI_PROJECT_DIR
    - pwd
    - echo $PATH
    - skaffold --help

  cache:
    key: skaffold-binary
    paths:
      - tools/

# doe:
#   image: byrnedo/alpine-curl
#   stage: deploy
#   script:
#     - echo "deploy"
#     - curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64
