stages:
  - prepare-build
  - test
  - build
  - post-build

# cache:
#   paths:
#     - ~/.cache/pip/

env_check:
  stage: prepare-build
  image: alpine
  script: 
    - sleep 1s
    - cat /etc/os-release

git_check:
  stage: prepare-build
  image: alpine/git
  script:
    - echo "check git revision"
    - git log -1

code_scan:
  stage: test
  image: newtmitch/sonar-scanner
  script:
    - echo "scanning"
    - sonar-scanner -Dsonar.projectKey=Tonyqu123_kaniko -Dsonar.organization=tonyqu123 -Dsonar.sources=. -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=d094b201296f509c2695b7ec41b4a54cb9c25df7

build_release:
  image: gcr.io/kaniko-project/executor:debug
  stage: build
  variables:
    CI_REGISTRY_IMAGE: "hub.eurekacloud.io/s4/build-kaniko-gitlab"
    CI_COMMIT_TAG: "release"
  before_script:
    - echo $CI_PROJECT_DIR
    - pwd
  script:
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/deploy/Dockerfile --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG

build_debug:
  image: gcr.io/kaniko-project/executor:debug
  stage: build
  variables:
    CI_REGISTRY_IMAGE: "hub.eurekacloud.io/s4/build-kaniko-gitlab"
    CI_COMMIT_TAG: "debug"
  before_script:
    - echo $CI_PROJECT_DIR
    - pwd
  script:
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/deploy/Dockerfile_debug --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG

doe:
  image: alpine
  stage: post-build
  script:
    - echo "post build"